# Generated by Django 5.2.8 on 2026-02-03 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='sections.section', verbose_name='Section'),
        ),
    ]
