# Generated by Django 5.2.8 on 2026-03-04 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_deleted_category_deleted_by_cascade'),
        ('expenses', '0005_alter_expense_amount'),
        ('sections', '0003_section_deleted_section_deleted_by_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='categories.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='sections.section', verbose_name='Section'),
        ),
    ]
