# Generated by Django 5.2.13 on 2026-04-15 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expense_deleted_expense_deleted_by_cascade_and_more'),
        ('sections', '0003_section_deleted_section_deleted_by_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='sections.section', verbose_name='Section'),
        ),
    ]
