# Generated by Django 5.2.8 on 2026-03-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_deleted_category_deleted_by_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
